README.md

Fixed typos / grammar in README

---

cmd/account.go
cmd/export.go
cmd/print.go
cmd/serve.go

Fixes minor grammatically issues/typos in error messages.

typos: fix minor typos in error messages

---

README.md
cmd/account.go
cmd/add.go
cmd/delete.go
cmd/export.go
cmd/import.go
cmd/open.go
cmd/print.go
cmd/root.go
cmd/search.go
cmd/serve.go
cmd/update.go

Removed the trailing dots which are a bit uncommon for descriptions and cleaned up the import sorting.

Cleaned up command imports and descriptions

---

internal/cmd/add.go

Default to webpage title, not URL, if user specifies no title

---

docs/shiori.postman_collection.json

Hello! Thanks for all of your work on Shiori.
This PR adds a Postman Collection covering most of the server endpoints in the `api` namespace. I'm hoping the community can use this documentation as a starting point for integrating with Shiori as a bookmarking backend.
Let me know what you think!

Adds Postman Collection for /api/ endpoints

---

internal/view/index.html
internal/view/login.html

Fix: Safari does not accept document.baseURI for cookie path

---

internal/view/content.html

Fix: Bookmark content displays Invalid Date if database is PostgreSQL

---

internal/cmd/root.go
internal/database/mysql.go
internal/view/login.html

Also specify charset for the connection. Full fix for #188.

Specify charset for MySQL connection

---

.githooks/pre-commit
.github/workflows/continuous-integration.yml
.gitignore
README.md
modd.conf

Add GitHub action to run `golint` and unit tests.

Continuous integration

---

Dockerfile

Dockerfile is now using local source instead of downloading the sources from github.
Build is now working.

bug: Docker build

---

internal/view/login.html
internal/webserver/handler-api.go

- Default session duration is 1h
- Increased session duration (when remember me is checked) is increased to 30d.
FIxes #229

fix: remember me session duration

---

internal/database/sqlite.go

It used an update and insert at the same time, since the virtual table
cannot have constrants nor upserts we need to try an update the
bookmark content to check for it's existence, inserting it only if the
update fails (don't affect any rows).
This will need to be improved in the future, since not all bookmark
updates require modification of the content table (in my case, I was
testing only updating tags).
Closes: #364

fix: update bookmark on sqlite database

---

internal/webserver/handler-api.go

Fixed a bug where the content of the article would archive but the
reader version would not be saved due to variable passing. Also made the
code easier to follow by following return principles.
Fixes #406

fix: bookmark content download

---

internal/webserver/handler-api.go

Using `database.CreateNewID` is very confusing. We should let the database engines create IDs directly instead of retrieving the last element in the sequence.
This is a first draft step that replaces the flow in the API, saving the bookmark first and then creating the archive with the ID provided by the database.
Requires #484  
FIxes #282 
Relates to #271

fix: remove CreateNewID usage from api handlers

---

internal/view/login.html

Added autofocus to the username on login page.

feat(frontend): username autofocus on login

---

internal/view/js/page/home.js

Fix issue #549 
Tested fix and working as expected now.
FIxes #549

Fix #549 reset page when searching for new tag

---

internal/webserver/handler-ui.go

Thanks, @andrigamerita
it checks acceptability of thumb before serve that to user
fix #578

thumb image will be not accesable anymore if it is private fix #578

---

internal/webserver/handler-api.go

This checks if the bookmark has a custom title and excerpt when calling the content download to preserve the custom attributes instead of overwriting them.
Fixes #632

fix: prevent bookmark overwrite on archive download

---

internal/webserver/handler-api.go

fix: title is never retrieved when adding bookmark

---

internal/cmd/server.go

Show Shiori version on server command

---

internal/webserver/handler-api.go

fix: title overwritten if user has defined it

---

internal/core/url.go

I encountered this issue myself while using shiori, so I figured I would have a go. I'm fairly new to git/programming, so... apologies in advance for any mistakes :)
Should fix #315

preserve fragment in URLs (#315)

---

internal/view/assets/js/page/setting.js

unify using token in save settings and remove unneeded variable.

fix: Remove unneeded variable and unify the way send token in header

---

.github/workflows/_test.yml

Adds a workflow step to run codecov reports on PRs

ci: add codecov reporting

---

Makefile

Generate coverage profile during unit testing so the Codecov action properly works

fix: generate coverage profile

---

internal/view/assets/js/component/bookmark.js
internal/view/content.html
internal/webserver/handler.go

https://caniuse.com/rel-noreferrer

fix: use noreferer to prevent exposing shiori instance url to archived websites

---

internal/view/assets/js/page/home.js

fix: incorrect endpoint in rename tags operation

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
internal/http/routes/api/v1/bookmarks.go

it is my bad that block swagger to finish without error.

fix : wrong response type for readable endpoint documentation

---

README.md

Add MariaDB to README as suggested in #1051

MariaDB in README.md

---

.github/workflows/_golangci-lint.yml
.golangci.yml

- Updates golangci-lint action and version to avoid broken CI flows

chore: update golangci-lint
