cmd/account.go, cmd/account_test.go, cmd/add.go, cmd/add_test.go, cmd/cmd_test.go, cmd/update.go, cmd/update_test.go, database/sqlite.go, main.go, model/model.go
Adds testing for **cmd** package. Adds a setup and teardown main test with a cmd test db as well as testing for account.
Closes #19 (tests issue)
=> Add unit tests for ./cmd

cmd/serve.go
Set server timeouts to avoid leaked descriptors on slow/disappearing clients or slow http attacks.
Fixes #51
=> Set server timeouts

main.go
This fixes an error when the `ENV_SHIORI_DB` is defined, it doesn't open a database file because the database file name isn't on the `databasePath` variable.
=> Prepend environment path to database path

.dockerignore, Dockerfile, README.md
This incorparates all changes from #27 (/cc @dexafree) rebased to current master and reduces the image size by using the multistaged build feature from docker. This also reduces the surface for attacks by reducing the amount of installed packages.
* Multistaged docker build - minimal Alpine Linux Image for the image
* Build/Setup-scripts to make it easier for newcomers to get started
* Extend documentation about how to run the docker container
=> Extended docker support

internal/webserver/utils.go
Fixes #182 
Not quite sure if this is the best fix. But I looked at the files under `view` and they seem to be `.css`, `.html`, `.js`, `.png`. The corresponding mimetypes are preset in a `map[string]string` var.
This seems to only happen on Windows, as the mimetypes are extracted from the registry as per [Golang docs](https://golang.org/pkg/mime/#TypeByExtension)
If there's no preset mimetype, it calls `mime.TypeByExtension` under the hood.
If you believe there's a less obtrusive fix, please let me know!
Cheers!
=> wrap mime.TypeByExtension with preset mimetypes

internal/view/login.html
Add `<form>` element, as some browsers won't autofill fields not contained in a form. Fixes #222
Remove username and password bindings, and explicitly read `input`s on login instead. Some browsers do not fire onChange events when a field is autofilled for security reasons, so Vue bindings don't register the change.
[More info](https://github.com/facebook/react/issues/1159#issuecomment-506584346).
=> Fix login autofill

internal/cmd/check.go, internal/cmd/delete.go, internal/cmd/export.go, internal/cmd/import.go, internal/cmd/open.go, internal/cmd/pocket.go, internal/cmd/print.go, internal/cmd/update.go
Replace `return` with `os.Exit(1)` as appropriate.
=> Exit with non-zero status when commands fail

internal/cmd/update.go
When -o parameter was used, the url parameter was accepted but ignored and not updated at all.
=> update url also when offline mode

Dockerfile
The current Dockerfile uses the golang:alpine image for the final image, which makes the final image much larger than needed.  This changes the final image to alpine and uses images from ghcr.io(It looks like these are ghcr.io official images pulled from dockerhub).  Also added a label to the image that will link the package to the repository.
=> Remove golang from final docker image

internal/core/processing.go, internal/webserver/handler-api-ext.go, internal/webserver/handler-api.go
Added an `async` field to POST /api/bookmark to allow the fetching of the bookmarks content to be asynchronous. The bookmarks updated content (thumbnail and so) will only be shown in the frontend after a refresh.
Along with that, the extension API call has been left untouched since I wasn't able to test it. We need to fix #269 before improving the webextension support.
Fixes: #302 
Blocked by: #367
=> feat: async content download when creating via api

internal/database/sqlite.go
Receive the following errors on startup after #367.
```
2022/02/14 11:23:42 error during database alert: SQL logic error: duplicate column name: owner (1)
2022/02/14 11:23:42 error during database alert: SQL logic error: duplicate column name: public (1)
```
Although these errors can be safely ignored since the columns exist, I think it would be safe to remove the alter table commands. The `owner` column was added to the `account` table in commit 0c4d75f77390ac2d2ba7a9436e2c2bc9b7102dd5 and the `public` column was added to the `bookmark` table in commit 20e89216f0b594e7aed231c5a31a71120d6ffba4 both over 2 years ago.  The only way I could see the removal being an issue is if the sqlite database was created before either of those commits and the tables haven't been updated by a later …
=> Remove unneeded alter table transactions from sqlite

internal/cmd/root.go
The migration to the latest dependencies made a change on the library we use to retrieve data directories. In this case the path we were trying to get should be `~/.local/share/shiori/` and we were returning `~/.local/share/shiori/shiori.db` **as a path**, so users upgrading from 1.5.0 experienced an error when shiori tried to create that path hierarchy. This should fix that problem but we still need to address #377 to prevent problems for people migrating from 1.5.0.
Relates to #291
=> fix: trying to mkdir over an incorrect data path

Gopkg.toml, go.mod
Heroku requires an extra line so it knows which go version to use.
https://github.com/heroku/heroku-buildpack-go#go-module-specifics
=> Add Go version for heroku

internal/database/sqlite.go
I came across this project a few days ago on HackerNews and I like it very much. After using it a bit more during the last few days, I notice that the performance degrades quickly. With 1187 bookmarks (40 pages), running the shiori server (using sqlite db) on MacBook Pro (16-inch, 2019) 2.6 GHz 6-Core Intel Core i7 took around 10 seconds to load and similar amount of time to switch between pages.
I managed to track down the culprit - it's the `LEFT JOIN` statements in the `GetBookmarks` and `GetBookmarksCount` methods in the `sqlite.go` that cause the slowness.
I'm not very familiar with the code base yet but it looks like we don't need `LEFT JOIN` in those methods. Removing it helps improving performance dramatically.
Before:
```
INFO[0000] Serve shiori in :8050 /
WARN[0005] GET …
```
=> sqlite: remove unneeded LEFT JOIN to improve performance

internal/core/url.go
This commit fixes URL malformation when trying to remove the utm social
query parameters from an URL, which upon finishing and reconstructing
would attach the equal symbol even if the original URL didn't have it.
This is a known Go "bug" [1] that isn't going to be "fixed". I quote
that because server side should behave the same for `?a=&b=1` and
`?a&b=1` for the `a` parameter, but sometimes that's not the case.
[1]: https://github.com/golang/go/issues/20820
Fixes #409
=> fix: url modification when query param is empty

.github/workflows/_buildx.yml
The build paths for amd64 binaries changed to `amd64_v1` and caused buildx to fail. I'm fixing this by moving the path to the ones expected by buildx.
=> fix: amd64 build paths

README.md, docs/API.md, docs/Configuration.md, docs/Frequently-Asked-Question.md, docs/Installation.md, docs/Screenshots.md, docs/Usage.md, docs/index.md
=> docs: migrate documentation from the wiki

internal/webserver/handler-ui.go
fix https://github.com/go-shiori/shiori/issues/445
last time I used embed.Fs to replace the assets generation, it turns out that the sub path is difference. For exmaple, When using assets generation, the `css` assets would be at `/css`, and when using embed.Fs it must be `css` since the embed.Fs doesn't allow sub path start with `/`: https://github.com/golang/go/blob/master/src/io/fs/fs.go#L41
=> fix invalid assets path when use webroot

internal/view/login.html, internal/webserver/handler-api.go
Deduplicated logic from backend and frontend where we needed to take the
login checkbox into account for both back and front codebases. Now the
backend will send the frontend the expire time calculated only in one
place.
This is part of a multi-step process that will store sessions in
database, but this will ease the maintenance of this section for now.
=> feat: session expire time from backend

docs/Usage.md
The example docker command given was invalid, as `docker run` operates on images, not containers. This is the closest working alternative using the same command, with another option being `docker exec containername shiori migrate` to operate on an existing container.
=> Fix docker migration script example

internal/database/database.go, internal/database/migrations/sqlite/0002_denormalize_content.down.sql, internal/database/migrations/sqlite/0002_denormalize_content.up.sql, internal/database/sqlite.go, internal/webserver/server.go
This PR is intended to address a range of performance regressions for the SQLite database.
Namely:
- Removed the slow JOIN for bookmark lists
- Reduced the number of queries for tags
Tested manually on 3k bookmarks with content. Last version ([7394b10](https://github.com/go-shiori/shiori/commit/7394b10)) returned main page in a second or two. Now it takes few, maybe tens of *milliseconds*.
Note that migration is required: `shiori migrate`.
Built an image for the test, now I use it myself: `docker.io/orhideous/go-shiori:1.5.2-perf-fix`
_P.S. There is definitely a room for improvement for another databases._
Fixes #408
=> Improve performance for sqlite queries

internal/database/migrations/sqlite/0002_denormalize_content.down.sql, internal/database/migrations/sqlite/0002_denormalize_content.up.sql
=> fix: remove manual transaction on sqlite migration 2

docs/API.md, docs/postman/shiori.postman_collection.json
Changed in pull request: https://github.com/go-shiori/shiori/pull/346
Since the API does not support numbers for the `remember` field in `/api/login`, I changed the documentation to make it a boolean instead of a number.
=> docs: fix remember represented as a number instead of a bool

go.mod, internal/cmd/add.go, internal/cmd/check.go, internal/cmd/delete.go, internal/cmd/export.go, internal/cmd/import.go, internal/cmd/open.go, internal/cmd/pocket.go, internal/cmd/print.go, internal/cmd/root.go, internal/cmd/update.go, internal/cmd/utils.go, internal/database/database.go, internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go, internal/webserver/handler-api-ext.go, internal/webserver/handler-api.go, internal/webserver/handler-ui.go, internal/webserver/utils.go
This PR makes a refactor of ways to handle error in db layer. I don't think it's proper to panic when there is an error in db actions. And every db action should be executed with a context passed by the caller.
=> refactor:pass ctx to db layer, return err instead of recover panic

internal/cmd/import.go
Check if the error from the `GetBookmark` call is `database.ErrNoRows` (query not returning results) and ignore it, allowing the importer to create the missing bookmarks.
Fixes #483
=> fix(import): check for no rows error

internal/database/pg.go, internal/database/sqlite.go
=> fix err in keyword searching

internal/cmd/export.go, internal/cmd/import.go, internal/cmd/pocket.go, internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go, internal/model/const.go
- Import command now respects the `ADD_DATE` or `LAST_MODIFIED` field, with the latter taking priority.
- Fixed a bug where saving a bookmarks would always set the modified date to the current date instead of using the set modified on the bookmark.
Fixes #121
=> fix: import should respect add_date or last_modified fields

internal/database/database_test.go, internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go
After a first bookmark save, all subsequent ones fail because the update query does not include an identifier and the update is done on all rows.
Add a test to create two different bookmarks.
Introduced by 05fee53bd0b7e81b5e74c4ae9efcbe213b563744
=> fix: failed to save bookmark: constraint failed: UNIQUE constraint failed: bookmark.url

internal/webserver/handler-api.go
Removed the usage of `panic()` when downloading a bookmark and simply return an error that has to be checked by implementations.
Right now the API will continue if the bookmark download fails (either sync or async) but will leave a log with the error cause, so the users have the bookmark stored even if the archival didn't actually happen (but can be done manually later on).
Fixes #459
Closes #495 (I actually forgot about this PR, sorry)
=> fix: avoid panic usage when downloading bookmark

internal/database/database_test.go, internal/database/sqlite.go, internal/database/sqlite_test.go
Replaces the dash (`-`) in keyword for the FTS5 arguments in SQLite, since that's a column token for the engine, so queries coming from the search with a dash where trying to find a column where the user would just want a keyword match.
Added some tests to handle this behavior.
Fixes #492
=> fix(db): avoid using dash in fts5 queries

internal/database/database_test.go, internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go, internal/webserver/handler-api-ext.go, internal/webserver/handler.go
- Modified the extension API to use the same save flow as the regular API, by generating the bookmark first and trying to archive it later. This will result in a stored bookmark even if the archiving fails.
- Switched the session priority, now the header has more priority than the cookie, witch should be the default, since the webserver sends the cookie and the extension requires the session anyway.
- Fixed the `DB.GetBookmark` method by handling the `sql.ErrNoRows` silently (since it already exposes a `bool`).
Fixes #517
=> fix(api-ext): use same save logic as the api

docker-compose.yaml, internal/cmd/add.go, internal/cmd/import.go, internal/cmd/pocket.go, internal/database/database.go, internal/database/database_test.go, internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go
This pull request removes the definition, implementation and usage of `CreateNewID` now that the `SaveBookmarks` implementation differentiates between a creation and a deletion, and make the creation homogenous between the CLI and the API, though not using common code for now.
Fixes #271
=> fix: remove createnewid usages

Dockerfile.compose
This should be `serve` not `server` 
server was causing it to freak out about the typo.
=> Remove typo in compose Dockerfile post-run command

internal/core/processing.go
Unfortunately, not all web servers are configured correctly. I found a [detailed comment on Stack Overflow](https://stackoverflow.com/a/54488403) from which it becomes clear that the MIME type `image/jpg` does not exist. But I am faced with the fact that on some servers, however, this type is specified. And as a result, the cover does not load.
Here is an example of a link: https://vc.ru/581066
```bash
$ curl -I -X GET "https://vc.ru/cover/fb/c/581066/1673501221/cover.jpg"
HTTP/2 200
content-type: image/jpg
```
Before and after this change:
=> feat: improve bookmark image detection

internal/webserver/handler-api.go
**Issue:**
Logging in to the web UI for the first time resulted in 301 redirect on v1.5.4. Only seems to be an issue on chromium based browsers (Brave, Chrome, Edge). Not an issue on Firefox as far as I can tell. 
**Solution:**
[JavaScript documents indicate cookie expires attribute should be UTC format ](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie). After cba5046 expiry date is returned in local time format instead of UTC. Updating backed to explicitly use UTC resolves the issue.
=> Use UTC for cookie expiry date in backend

internal/webserver/handler-api-ext.go
After I changed the code, I noticed that next-api (#497) seems to have fixed the problem, so you might consider merging this pr if next-api is not released in time.
=> fix: browser ext cannot archive and update bookmark.

internal/cmd/root.go, internal/cmd/utils.go, main.go
For improved debugging convenience, add some log flags in root command
- log-level: specify log level, default info
- log-caller: whether log `file:lineno` or not, default false
- log FullTimestamp
=> Add log args for root command

internal/core/ebook.go
This PR fix problem that download mechanism tried to get data/image.
It should not happen (they are not a real URL that point to the specific server, they are actual data)
by excluding them, we can handle data/image too.
Caliber or modern browser can handle this kind of links itself.
Will fix #645
for [Future reference](https://en.wikipedia.org/wiki/Data_URI_scheme)
=> fix download data image fix #645

.github/workflows/_delete-registry-tag.yml
Trying to fix the action that cleans up the docker images from prs
=> fix: package-name in cleanup tag

internal/cmd/root.go
=> Proper SQLite default database and warn SHIORI_DBMS users

.github/workflows/_buildx.yml, .github/workflows/pull_request.yml
=> Fix CI incorrectly tagging RC releases and disables docker builds on forks

docs/Installation.md
This PR updated `Installation.md`, to add guidance for deploying Shiori with Fly.io.
As many people look for self-hosting bookmark service, it would be great if the docs can provide them with a straight-forward and easy way to quickly set up an instance without diving into too much tech details. 
This change is only a doc update, and doesn't affect any functionality of the project.
This PR has the same content as #705, but pushing to `fmartingr/issue663` per requested by @fmartingr .
=> [docs update] Add guidance for deploying with Fly.io

internal/database/database_test.go, internal/database/pg.go, internal/database/sqlite.go
The current queries are built by concatenating strings in the code, rather than in the database, meaning we lose sanitization on the database side.
This PR adds a new test that checks queries with some special characters to avoid failures, while doing:
- String concatenation for `LIKE` queries in the query directly
- Properly quoting FTS5 search queries in SQLite
- Properly parsing double quotes in SQLite queries for FTS5.
Fixes #717
=> fix(db): handle usage of special characters in searches

.gitignore, docker-compose.yaml, docs/Configuration.md, internal/database/database.go
Mysql connection string update, docs update
Fixes #729
=> fix: properly parse mysql connection string, docs update

go.mod, go.sum, internal/config/config.go, internal/http/routes/legacy.go
`go-epub` will use uuid v5 #679  and we will have two version of dependency for same functionality. just update to v5
=> deps: upgrade github.com/gofrs/uuid to v5

Makefile, internal/view/assets/js/page/home.js, internal/view/assets/js/page/setting.js, internal/view/login.html
- Properly store the JWT token in the local storage
- Use a secret locally to prevent logouts when restarting the dev server
- Make it so all API requests from the frontend sends then `Authorization` header.
There's still something to solve when we require the user to load an URL that is not an API route (bookmark archive, readable, ebook), since those won't be API calls per se, but load content directly in the browser. Right now they work because we still maintain the cookie with the session around, but we need to figure out the best way to migrate that to the new routes. Probably a cookie is the best solution, but we need to think what to put in it.
=> feat: use new JWT auth in all frontend API calls

scripts/styles_check.sh, scripts/swagger_check.sh
currently if we use `make styles-check` or `make swag-check` those scripts return error if we have uncommit file even if they are not related to CSS or swagger.
this try to fix #737
=> fix: styles-check and swag-check monitor just needed directory not project root

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/core/processing.go, internal/http/routes/api/v1/auth_test.go, internal/model/account.go, internal/view/assets/js/page/home.js, internal/view/assets/js/page/setting.js, internal/view/content.html, internal/view/index.html, internal/webserver/handler-api.go
add a settings for active generate ebook by default.
- web extension and command line until we finish work on #369 
fix #720
=> add create ebook by default in settings

docs/CLI.md, docs/index.md
Added `Add bookmark` instruction and examples in CLI documentation.
=> Add Documentation>CLI>Add bookmark

docs/Configuration.md
=> docs: updated configuration page

Makefile, internal/cmd/root.go, internal/cmd/server.go, internal/config/config.go, internal/config/config_test.go
- Disable the configuration OS Lookuper to prevent errors when setting configuration via environment variables. All variables but `HOSTNAME` should use the `SHIORI_` prefix.
- Added tests coverage for the `config.go` file
- Small refactor under `Config.SetDefaults`
- With `LOG_LEVEL=DEBUG`, all the configuration variables are logged on server startup.
Fixes  #787
=> fix: force usage of shiori prefix for environment variables in configuration

.github/workflows/docker/Dockerfile.ci, Dockerfile, Dockerfile.compose
Updated alpine to 3.19 and golang to 1.21 in dockerfiles.
=> deps: updated docker image versions

docs/Installation.md
In the (currently) provided Kubernetes deployment manifest the securityContext is missing, this results in Shiori crashing with a vague "out of memory" error. This pull request adds the securityContext with the same uid and gid values as in the Docker image (1000), fixes #791.
=> Add securityContext to provided Kubernetes manifest

.github/workflows/_buildx.yml
Use correct tag names when releasing a new version:
- tag `vx.x.x` -> `vx.x.x` & `latest`
- tag `vx.x.x-rc.x` -> `vx.x.x-rc.x` & `dev`
- pr -> `pr-xxx`
Fixes #863
=> fix(ci): use correct tag names on version bump

internal/http/routes/api/v1/bookmarks.go
This pull request removes logic for unfinished enpoints for the v1 API
=> fix: remove unfinished endpoints

internal/view/assets/js/page/setting.js
Some API calls were using an absolute path ignoring the `base href` element thus not working/pointing where it shouldn't.
Fixes #870
=> fix: api calls using absolute urls

.github/workflows/_gorelease.yml
gorelease update because  `--rm-dist` deprecated
https://goreleaser.com/deprecations/#-rm-dist
=> fix: replace --rm-dist with --clean

.github/workflows/_buildx.yml
Modify the buildx CI pipeline to avoid tagging `latest` all PRs that go into master.
=> fix(ci): prevent tagging latest every merge into master

docs/Installation.md
Add *Managed Hosting* section and PikaPods as provider.
=> Add PikaPods hosting option

.golangci.yml
Replaces the deprecated Golang-CI option `run.skip-dirs` with `issues.exclude-dirs`.
=> fix(ci): renamed deprecated golangci property

internal/http/middleware/auth_test.go, internal/http/response/response.go, internal/http/response/shortcuts.go, internal/http/routes/api/v1/api.go, internal/http/routes/api/v1/bookmarks.go, internal/http/routes/api/v1/bookmarks_test.go, internal/http/routes/api/v1/tags.go, internal/http/routes/api/v1/tags_test.go, internal/model/http.go, internal/testutil/response.go
- Ensures that the connection is aborted from the Auth middleware when the authentication is unsuccessful.
- Modified the main middleware test to ensure that we are not filtering out extra response data
- Added helper methods to `testutil.TestResponse`
- Fixed some typos
- Fixed tests for the tags and bookmarks api v1
=> fix: authentication flow should abort early

internal/database/mysql.go, internal/database/pg.go, internal/database/sqlite.go
Fix potential panic by checking `err` before doing comparisons over it.
Fixes #904
=> fix: not checking for nil-pointer errors on migrations

Dockerfile, internal/http/routes/api/v1/bookmarks.go
- Ensures the `/tmp` folder is present in the docker container since it's required to download archives and ebooks.
- Adds a logger to the `/api/v1/bookmark/cache` endpoint to show errors to the admin.
=> fix: ensure tmp folder is present on docker container

internal/view/archive.html
Fixes the "View original" link in the archive page.
Closes #930
=> fix: incorrect original link in archive page

.goreleaser.yaml
This PR adds the version to the archive filename of the goreleaser dist bundles to prevent errors on releases
=> fix: add version to goreleaser archive filename

.goreleaser.yaml
This change makes goreleaser ignore release candidate tags when comparing the previous version of a stable release, generating a proper changelog instead of just the comparison with the latest RC.
=> fix(ci): ignore nightly tags when comparing stable releases

internal/database/sqlite_noncgo.go
Fix broken build on FreeBSD after commit 02247b215b2fa1c1c18f651561092290ed2a5058.
FIxes #947
=> fix: add `freebsd` flag to nonCGO build (#947)

scripts/styles.sh
update message in `style.sh` to use baseline version instead of sde refrence to this
https://github.com/oven-sh/bun/issues/67 Thanks @fmartingr
=> chore: change warning message for bun on cpus without avx2

Dockerfile.compose
Resolves https://github.com/go-shiori/shiori/issues/986 by updating Docker Go image version to match version required in `go.mod`.
=> chore: bump compose go version to match go.mod

docs/Frequently-Asked-Question.md
From #999 
Instructions for Mac LaunchAgent so the Shiori server will start at login automatically.
Note:
I tested on my Mac but it would be nice if someone else can also do a test to make sure.
Thanks!
=> docs: add Mac LaunchAgent instructions

.github/workflows/_gorelease.yml, .goreleaser.yaml, scripts/buildx.sh
- Use a fixed goreleaser version in CI
- Updated the `.goreleaser.yml` file, addressing the warnings.
- Rename the `arm64_v8.0` file to remove the `_v8.0` suffix which was breaking buildx builds.
=> ci: fixed goreleaser latest version binary name breaking buildx

internal/view/assets/js/component/login.js, internal/view/index.html
- Preventing unnecessary login form display during page loads
- Improving session validation
- Fixes logout behavior
=> fix: login component behavior when logging out and refreshing the page

internal/cmd/pocket.go
Recently Pocket changed the format of their data export function, switching from HTML files to a zipped folder containing CSV files, delivered in parts of up to 10000 bookmarks.
Other bookmark managers were also affected by this, as seen here: https://github.com/hoarder-app/hoarder/issues/570
This patch allows the `pocket` sub-command to handle these files correctly, expanding it's functionality to import both HTML and CSV files, as I believe the ability to import older exports may still be useful. This is done by a simple file extension check, which I think will suffice for most users.
Note that the command still does not process the multiple part files explicitly, so the user has to import them one by one, which I don't think will be too much of a hassle for the user either way. :)
I …
=> feat: allow import of newer pocket data export files in csv format

.github/workflows/pull_request.yml, .github/workflows/pull_request_closed.yml
- Ignore builds for dependabot (since they do not have push permissions)
- Ignore `delete-tag` step for closed pull requests coming from forks
=> ci: ignore build steps for dependabot

.github/workflows/version_bump.yml
Fixes #1034 
Removes a incorrect `if` condition in the CI that prevented the Alpine images from being built on new releases.
=> ci: fix alpine latest not being built

docs/Installation.md
When trying to generate ebooks in a kubernetes hosted instance, I noticed a failure due to permissions in `/tmp`. 
The best way to make sure that `/tmp` acts as expected, is to provide an `emptyDir` volume which will get cleaned up on container restart, which would be the expected behavior for a `/tmp` folder.
=> docs(kubernetes): add tmp volume

internal/view/archive.html
Setting the base URL is required for the archived page to render properly when a `--webroot` is in use.
I tested the use of the webroot by running a local nginx configured to be a reverse proxy (see configuration below) and then running shiori:
```shell
go run main.go server --webroot shiori --port 8081
```
Prior to the fix my archived page looks like this:
And with the fix it looks like this:
I tested without `--webroot` and confirm that behavior still works.
I tested on MacOS by installing nginx `brew install nginx` and then editing `/opt/homebrew/etc/nginx/nginx.conf` to look like:
```nginx
worker_processes  1;
events {
worker_connections  1024;
}
http {
include       mime.types;
default_type  application/octet-stream;
sendfile        on;
keepalive_timeout  65;
server {
listen …
```
=> fix: webroot not working in archive view

internal/http/response/shortcuts.go, internal/http/routes/bookmark.go, internal/http/routes/bookmark_test.go, internal/view/assets/js/component/login.js, internal/view/index.html
Bug introduced in #1017 
The login component was not properly handling the `dst` parameter, and the backend was redirecting to the (now non-existant) `/logjn` route.
Modified the backend to properly redirect to `/` when the user is not authenticated and added `dst` parameter support to the login component.
=> fix: login redirect not working properly after component refactor

internal/database/migrations/mysql/0001_initial_account.up.sql, internal/database/mysql.go
This pull request addresses the default value syntax for JSON columns in MySQL tables. The changes ensure consistency and correctness in the default value assignment for JSON columns.
https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit
FIxes #1009
=> fix: use mysql json default as expression

Makefile, docker-compose.yaml, docs/Contribute.md, internal/cmd/root.go, internal/config/config.go, internal/config/config_test.go, internal/view/index.html, testdata/nginx.conf
Fixes some issues regarding the usage of the `RootPath` configuration, including validation of the attribute requiring a slash at the end to avoid issues in configurations.
Also, added a `nginx` service to the development compose file to locally test this feature.
=> feat: fixes to webroot feature and improvements to development using it

internal/view/assets/js/component/login.js
When writing a cookie using document.cookie, the expires value should use the UTCString format.
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie
If expires is set incorrectly, the cookie will expire at the end of session and thumbnail will fail to load.
=> fix: incorrectly set cookie's expires value in login.js

.githooks/pre-commit, .github/workflows/_test.yml, docker-compose.yaml, docs/Contribute.md, internal/database/mysql_test.go
Modifies the docker compose and github workflow files to use the oldest supported database engines, adding mysql into de mix, so we can run the test suite against all of them, helping identifying database bugs earlier.
#1009
=> test: test all supported engines on their oldest supported releases

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/http/handlers/api/v1/accounts_test.go, internal/http/handlers/api/v1/auth.go, internal/http/handlers/api/v1/auth_test.go, internal/http/handlers/bookmark.go, internal/http/handlers/legacy.go, internal/http/handlers/legacy_test.go, internal/http/middleware/auth.go, internal/http/middleware/auth_test.go, internal/http/server.go, internal/view/assets/js/component/login.js, internal/view/assets/js/page/base.js, internal/view/index.html, internal/webserver/handler.go, internal/webserver/server.go
This pull request includes several changes aimed at removing the legacy session handling and improving the authentication process by using token-based authentication. The most important changes include the removal of the legacy session handling, updating the login and logout handlers, and ensuring the token is properly managed in the client-side code.
* [`internal/http/handlers/api/v1/auth.go`](diffhunk://#diff-f045a095cf5a4259bb9de413ed435e79ae16ac2cd421cc9afc154cc08a89e6deL44-R43): Removed the legacy session ID handling and related code from the `HandleLogin` function. [[1]](diffhunk://#diff-f045a095cf5a4259bb9de413ed435e79ae16ac2cd421cc9afc154cc08a89e6deL44-R43) [[2]](diffhunk://#diff-f045a095cf5a4259bb9de413ed435e79ae16ac2cd421cc9afc154cc08a89e6deL75-L84)
* …
=> fix: auth validation on existing sessions, rely on token only

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/cmd/root.go, internal/database/database.go, internal/database/database_tags.go, internal/database/database_tags_test.go, internal/database/database_test.go, internal/database/mysql.go, internal/database/mysql_test.go, internal/database/pg.go, internal/database/pg_test.go, internal/database/sqlite.go, internal/database/sqlite_noncgo.go, internal/database/sqlite_openbsd.go, internal/domains/tags.go, internal/domains/tags_test.go, internal/http/handlers/api/v1/tags.go, internal/http/handlers/api/v1/tags_test.go, internal/model/database.go, internal/model/db.go, internal/model/domains.go, internal/model/tag.go, internal/testutil/http.go, internal/view/assets/js/page/home.js, internal/webserver/handler-api.go
Added missing stuff for #658:
- Allows to retrieve the bookmark tag count on tags
- Allows to filter tags by bookmark ID
- Refactored the database logic to have common methods for all engines to reuse code with the sql builder
=> feat: allow tag filtering and count retrieval via api

docs/Configuration.md
It looks like the `SHIORI_HTTP_ROOT_PATH` replaced the `SHIORI_WEBROOT` environment variable. Also, I needed to add the trailing `/` to the NGINX location config (i.e. `location /shiori/`) to get the reverse proxy configuration to work.
=> docs: fix issue with reverse proxy webroot configuration

.github/workflows/_buildx.yml
- Push versioned images (v*) to shioriapp/shiori on DockerHub
- Maintain existing GitHub Container Registry publishing
- Add DockerHub authentication for tagged releases only
- Preserve backward compatibility for master and PR builds
=> ci: add DockerHub publishing for versioned releases
